//
//  IAutogeneratedCredentialsFactory.swift
//  CallMeSdk
//
//  Created by Matteo Cioppa on 18/10/22.
//

import Foundation

protocol IAutogeneratedCredentialsFactory {
    static func makeCredentials(forRealm realm: String) -> UserSipDataAccount
}
