//
//  AutogeneratedCredentialsFactory.swift
//  CallMeSdk
//
//  Created by Matteo Cioppa on 17/10/22.
//

import Foundation

final class AutogeneratedCredentialsFactory: IAutogeneratedCredentialsFactory {
    static func makeCredentials(forRealm realm: String) -> UserSipDataAccount {
        let username = generateUsername()
        let password = UUID().uuidString

        return UserSipDataAccount(
            username: username,
            password: password,
            type: .TYPE_AUTOGENERATED,
            realm: realm
        )
    }

    private static func generateUsername() -> String {
        let currentDate = Date()
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyMMddhhmmss"
        return "cfw" + dateFormatter.string(from: currentDate)
    }
}
