//
//  UserSipData.swift
//  CallMeSdk
//
//  Created by Matteo Cioppa on 05/09/22.
//

import Foundation

enum UserSipDataAccountType: String, Codable {
    case TYPE_EXISTING
    case TYPE_AUTOGENERATED
}

struct UserSipData: Codable {
    let currentSipCredentialsType: UserSipDataAccountType
    let existingSipCredentials: UserSipDataAccount?
    let autogeneratedSipCredentials: UserSipDataAccount

    var currentSipCredentials: UserSipDataAccount {
        switch currentSipCredentialsType {
        case .TYPE_EXISTING:
            if let existingSipCredentials = existingSipCredentials {
                return existingSipCredentials
            } else {
                fatalError("invalid existing sip credentials")
            }
        case .TYPE_AUTOGENERATED:
            return autogeneratedSipCredentials
        }
    }
}

struct UserSipDataAccount: Codable {
    let username: String
    let password: String
    let type: UserSipDataAccountType
    let realm: String
}
